# cert-manager base configuration
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.18.2/cert-manager.yaml

labels:
  - pairs:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/component: cert-manager
