apiVersion: v1
kind: Service
metadata:
  name: dumbkv-service
  labels:
    app: dumbkv
spec:
  type: ClusterIP # Internal service
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: dumbkv
