# PostgreSQL base configuration
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql.yaml
  - postgresql-secret.yaml

labels:
  - pairs:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/component: database
